### PR TITLE
Task/damage controller

### PR DESCRIPTION
**Pull request by lassombra**
Includes #167 and #168 - attaches a dummy damage controller if one isn't present (note that there is not currently a damage controller proxy)

### CODE REVIEW

**Comment by katycat5e** [comment]
Since the resource containers all use the same proxy fields, is it possible to replace the several different proxy scripts with a single one with a resource type drop down? And then have the proxy replacer choose the correct concrete implementation based on that field?

**Comment by lassombra** [comment]
> Since the resource containers all use the same proxy fields, is it possible to replace the several different proxy scripts with a single one with a resource type drop down? And then have the proxy replacer choose the correct concrete implementation based on that field?

This is certainly possible but has a couple of drawbacks because of losing 1:1 to vanilla.

1. Users inspecting vanilla prefabs can add "Proxy" and get matching behavior with 1:1 - with this they'll have to go to our docs or use intuition to figure out what to add
2. The approach used here to map proxies gets more boilerplate.  Right now for 1:1 to vanilla, adding a proxy mapping is a two line affair which doesn't repeat itself and uses generic functions to just "magically" do its thing.  I can definitely work on refining this.

What that would look like:

```
using AutoMapper;
using CCL.Types.Proxies.Resources;
using LocoSim.Definitions;
using System.ComponentModel.Composition;
using UnityEngine;

namespace CCL.Importer.Proxies.Resources
{
    [Export(typeof(IProxyReplacer))]
    public class ResourceContainerProxyAutoMapper : Profile, IProxyReplacer
    {
        public ResourceContainerProxyAutoMapper()
        {
            CreateMap<ResourceContainerProxy, CoalContainerDefinition>();
            CreateMap<ResourceContainerProxy, FuelContainerDefinition>();
            CreateMap<ResourceContainerProxy, OilContainerDefinition>();
            CreateMap<ResourceContainerProxy, SandContainerDefinition>();
            CreateMap<ResourceContainerProxy, WaterContainerDefinition>();
        }

        public void ReplaceProxies(GameObject prefab)
        {
            foreach (var resourceContainerProxy in prefab.GetComponentsInChildren<ResourceContainerProxy>())
            {
                switch (resourceContainerProxy.type)
                {
                    case ResourceContainerType.Coal:
                        resourceContainerProxy.MapComponent<ResourceContainerProxy, CoalContainerDefinition>();
                        break;
                    case ResourceContainerType.Fuel:
                        resourceContainerProxy.MapComponent<ResourceContainerProxy, FuelContainerDefinition> ();
                        break;
                    case ResourceContainerType.Oil:
                        resourceContainerProxy.MapComponent<ResourceContainerProxy, OilContainerDefinition>();
                        break;
                    case ResourceContainerType.Sand:
                        resourceContainerProxy.MapComponent<ResourceContainerProxy, SandContainerDefinition>();
                        break;
                    case ResourceContainerType.Water:
                        resourceContainerProxy.MapComponent<ResourceContainerProxy, WaterContainerDefinition>();
                        break;
                    default:
                        CCLPlugin.Warning("Attempted to map a Resource Container Proxy of an unknown resource type, doing nothing");
                        break;
                }
            }
        }
    }
}
```

There's probably a way to structure things so that it's a bit less boilerplate to do this based on the type, some kind of abstract method I have some ideas, so let me know if you'd like me to pursue this approach.

**Review by katycat5e — APPROVED** [review]
We can keep the current solution, it doesn't seem like that much benefit to change it at this point, since like you said it's really just replacing code in one place with code in another.

**Comment by lassombra** [comment]
Well, I did some consideration and figured out how I can reduce the boilerplate down to just

```
using CCL.Types.Proxies.Resources;
using LocoSim.Definitions;
using System.ComponentModel.Composition;

namespace CCL.Importer.Proxies.Resources
{
    [Export(typeof(IProxyReplacer))]
    public class CoalContainerProxyReplacer : ProxyReplacer<ResourceContainerProxy, CoalContainerDefinition> {
        protected override bool CanReplace(ResourceContainerProxy sourceComponent)
        {
            return sourceComponent.type == ResourceContainerType.Coal;
        }
    }
    [Export(typeof(IProxyReplacer))]
    public class FuelContainerProxyReplacer : ProxyReplacer<ResourceContainerProxy, FuelContainerDefinition> {
        protected override bool CanReplace(ResourceContainerProxy sourceComponent)
        {
            return sourceComponent.type == ResourceContainerType.Fuel;
        }
    }
    [Export(typeof(IProxyReplacer))]
    public class OilContainerProxyReplacer : ProxyReplacer<ResourceContainerProxy, OilContainerDefinition>
    {
        protected override bool CanReplace(ResourceContainerProxy sourceComponent)
        {
            return sourceComponent.type == ResourceContainerType.Oil;
        }
    }
    [Export(typeof(IProxyReplacer))]
    public class SandContainerProxyReplacer : ProxyReplacer<ResourceContainerProxy, SandContainerDefinition> {
        protected override bool CanReplace(ResourceContainerProxy sourceComponent)
        {
            return sourceComponent.type == ResourceContainerType.Sand;
        }
    }
    [Export(typeof(IProxyReplacer))]
    public class WaterContainerProxyReplacer : ProxyReplacer<ResourceContainerProxy, WaterContainerDefinition> {
        protected override bool CanReplace(ResourceContainerProxy sourceComponent)
        {
            return sourceComponent.type == ResourceContainerType.Water;
        }
    }
}
```

Including it at this point definitely opens the door a bit wider for how proxies get designed, so I'd say it's worth considering, let me know.

**Comment by katycat5e** [comment]
Works for me, if you're happy with it you can go ahead and merge.

**Comment by lassombra** [comment]
Alright, I committed that version that enables multiple destinations from one proxy - it's added a bit more robustness to the proxy replacer so that it's still possible to do quite a bit without fully customizing the replacer.

Readme has been updated.

Also I don't have write access so I can't merge - but wanted you to take a look at the latest differences anyways.

**Review by katycat5e — APPROVED** [review]
I changed the org permissions, should be able to merge now I think

**Pull request merged**
